_parent_: projects/neuralangelo/configs/base.yaml
data:
    num_images: 38
    readjust:
        center:
        - 0.0
        - 0.0
        - 0.0
        scale: 1.0
    root: /home/cloud/datasets/phone_clean/dense
    train:
        image_size:
        - 1079
        - 1921
    type: projects.neuralangelo.data
    val:
        image_size:
        - 300
        - 534
model:
    appear_embed:
        dim: 8
        enabled: true
    object:
        sdf:
            encoding:
                coarse2fine:
                    init_active_level: 4
            mlp:
                inside_out: false
