_parent_: projects/neuralangelo/configs/base.yaml
data:
    num_images: 207
    readjust:
        center:
        - 0.0
        - 0.0
        - 0.0
        scale: 1.0
    root: /home/cloud/datasets/scene1/dense
    train:
        image_size:
        - 1076
        - 1914
    type: projects.neuralangelo.data
    val:
        image_size:
        - 300
        - 533
model:
    appear_embed:
        dim: 8
        enabled: true
    background:
        enabled: false
    object:
        sdf:
            encoding:
                coarse2fine:
                    init_active_level: 8
            mlp:
                inside_out: true
    render:
        num_samples:
            background: 0
